# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
- page: home
  url: /
  icon:

# - page: 前端
#   url: /categories/前端/
#   icon:
# - page: 后端
#   url: /categories/后端/
#   icon:
# - page: 工具
#   url: /categories/工具/
#   icon:
# - page: 时间轴
#   url: /archives/
#   icon:

## favicon
favicon: /favicon.ico

## Feed
rss: /atom.xml

## Carousel
carousel:
  img: ##'./img/head-img.jpg'
  url: ## 'https://promotion.aliyun.com/ntms/act/qwbk.html?userCode=xs0pypd2'

# Settings for each gadget

## widgets
widgets:
##  - search
##  - notification
##  - social
  - category
  - archive
  - tagcloud
##  - friends
##  - stick

## search for
jsonContent:
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: false
    tags: false

## Website announcement settings
notification: |-
            <p>Theme Snippet v1.2.1 The version is online! Welcome update <br/>
            Theme download：<a href="https://github.com/shenliyang/hexo-theme-snippet" title="fork me" target="_blank">Snippet theme</a> <br/>
            Theme use：<a href="https://github.com/shenliyang/hexo-theme-snippet/blob/master/README.md#常见问题" title="" target="_blank">Common use problem</a> <br/>
            <hr/>Accept contributions, including not limited to submitting questions and requirements, fixing the code. welcome Pull Request<br/>Support theme：<a href="https://github.com/shenliyang/hexo-theme-snippet/stargazers">Star</a>
            </p>

## Social settings
social:
 - name: Github
   icon: git
   href: //github.com/shenliyang
 - name: mailbox
   icon: envelope-o
   href: mailto:snippet@91h5.cc
 - name: Contact QQ
   icon: qq
   href: /
 - name: WeChat
   icon: weixin
   href: /
 - name: QQgroup
   icon: users
   href: /
 - name: RSS
   icon: feed
   href: /atom.xml

## Article classification settings
cate_config:
   show_count: true
   show_current: true

## Article archive settings
arch_config:
   type: 'monthly'
   format: 'YYYY/MM'
   show_count: true
   order: -1

## Tag cloud settings
tagcloud:
  tag3d: false
  textColour: '#444'
  outlineMethod: 'block'
  outlineColour: '#FFDAB9'
  interval: 30
  freezeActive: true
  frontSelect: true
  reverse: true
  wheelZoom: false

## Friend chain setting
links:
  - Hexo official website: https://hexo.io/


# Theme custom personalized configuration

## Website slogan
branding:

## Set banner background image
banner:
    img: https://www.lukastomek.info/static/banner.jpg

## Home list bottom panel
homePanel: true

## Thumbnail custom random image
defaultImgs:
  -

## Intercept the first page of the article to describe the number of words
excerptLength: 120

## Whether to open the article directory
toc: true

## Code highlighting configuration
highlightTheme:

## Bootstrap configuration
bootstrap:

## ICON configuration
fontAwesome:

## Article expiration reminder function 0 means off
warning:
  days: 0
  text: 'This article was published before %d days, and the content in the article may be outdated.'

## Statement in the article
declaration:
  enable: true
  title: 'Reprint statement'
  tip: |-
      For commercial reprint, please contact the author for authorization. For non-commercial reprint, please indicate the source. © <a href="" target="_blank">Snippet</a>

## Article reward
reward:
  alipay: ''
  wepay: ''
  tip: Appreciation is not a rogue encouragement

## Subject review

## Valine Review
valine:
   enable: false
   appId: xOKV9J4UeQAtVkvnJC7Kq2Jn-gzGzoHsz
   appKey: erIpQac4azoCmgfBB7Dl9maa
   placeholder: say something
   notify: false
   verify: true
   avatar: mm
   meta: nick,mail
   pageSize: 10

### Easy comment (requires ICP record)
changyan:
  enable: false
  appid:
  conf:

### Come to force
livere:
  enable: false
  livere_uid: MTAyMC8zMzA1MS85NjEz

## Gitalk Review
gitalk:
   enable: false
   clientID:
   clientSecret:
   repo:
   owner:
   admin:
   perPage:
   distractionFreeMode: true

### Disqus reviews
disqus:
  enable: false
  shortname: snippet
  count: false

### Gitment comment (long-term update, not recommended)
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  perPage: 10

### Friendship comment (service is unstable)
uyan:
  enable: false
  uyan_id: 1966422

## Website visitor statistics
visit_counter:
   site: false
   page: false

## Website access statistical analysis

### Net Meng CNZZ statistics
cnzz_analytics:

### Baidu statistics
baidu_analytics:

### Google statistics
google_analytics:

### Tencent analysis
tencent_analytics:

### Baidu Site Certification
baidu_site_verification:

### Baidu automatic push
baidu_push: false

# Website theme configuration
since: 2017
robot: 'all' ### Control search engine crawling and indexing behavior, the default is all
version: 1.2.3
